export const SHARED_ASSET_DOMAIN = "assets.orrylo.com";

export const SHARED_ISSUER_CANDIDATE =
  "GBR7SEZD4ITXQPAWEVBX2BULS76ERDRTRMIS3LUYKZ7DNLGZZ6ASSETS";

export const RYLO_ISSUER_CANDIDATE =
  "GCKB453UWEFLJQY4TVW7I7NZV3ZNVUCZZS6KKIKJZVF75WM2VEORRYLO";
